// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package git

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"

	"github.com/Mirac61/lifelog/web/templ/ui"
)

// The view swaps in place instead of navigating; the timings match the
// #gitview fade in style.css.
const swapView = "innerHTML swap:120ms settle:150ms"

// viewNav points at a year of a type. Year 0 means "no such year" — the zero
// Nav renders the step disabled.
func viewNav(eventType string, year int) ui.Nav {
	if year == 0 {
		return ui.Nav{}
	}
	return ui.Nav{
		Get:    fmt.Sprintf("/git/view?type=%s&year=%d", eventType, year),
		Target: "#gitview",
		Swap:   swapView,
	}
}

func typePills(page GitPage) []ui.Pill {
	pills := make([]ui.Pill, 0, len(page.TypeOptions))
	for _, opt := range page.TypeOptions {
		pills = append(pills, ui.Pill{
			Label:  opt.Label,
			Active: opt.Value == page.Type,
			Nav:    viewNav(opt.Value, page.Year),
		})
	}
	return pills
}

func yearStepper(page GitPage) ui.Stepper {
	return ui.Stepper{
		Value:     fmt.Sprint(page.Year),
		Prev:      viewNav(page.Type, page.PrevYear),
		PrevLabel: "Vorheriges Jahr",
		Next:      viewNav(page.Type, page.NextYear),
		NextLabel: "Nächstes Jahr",
	}
}

func GitControls(page GitPage) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.Pills(typePills(page)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Steps(yearStepper(page)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
